// #include <stdbool.h>

#ifndef POOLBOT_H
#define POOLBOT_H

#define IFACE_MS 100
#define DEFAULT_DURATION_M 60l

#define PIN_CLEANER_PUMP 0  // TODO

#define PIN_HEAT 0 // TODO

#define VALVE_MOVE_TIME_MS 35000
#define PIN_VALVE_IN_SPA 0  // TODO
#define PIN_VALVE_OUT_SPA 0  // TODO
// #define PIN_FLOW_SWITCH 0  // TODO
// #define PIN_VALVE_CURRENT 0  // TODO
#define PIN_PUMP_STOP 0 // TODO
#define PIN_PUMP_SPEED_STEP_1 0 // TODO
#define PIN_PUMP_SPEED_STEP_2 0 // TODO

#define PIN_BUTTON_MENU_UP 13
#define PIN_BUTTON_MENU_OK 12
#define PIN_BUTTON_MENU_DOWN 11

#define PIN_BUTTON_SPEED_OFF 53
#define PIN_BUTTON_SPEED_MIN 51
#define PIN_BUTTON_SPEED_LOW 49
#define PIN_BUTTON_SPEED_HI 47
#define PIN_BUTTON_SPEED_MAX 45

#define PIN_BUTTON_MODE_SPA 52
#define PIN_BUTTON_MODE_SPILL 50
#define PIN_BUTTON_MODE_POOL 48
#define PIN_BUTTON_MODE_CLEAN 46


#define NUM_BUTTONS 12

const byte INPUT_BUTTON_PINS[] = {PIN_BUTTON_MENU_UP, PIN_BUTTON_MENU_OK, PIN_BUTTON_MENU_DOWN, PIN_BUTTON_SPEED_OFF, PIN_BUTTON_SPEED_MIN, PIN_BUTTON_SPEED_LOW, PIN_BUTTON_SPEED_HI, PIN_BUTTON_SPEED_MAX, PIN_BUTTON_MODE_SPA, PIN_BUTTON_MODE_SPILL, PIN_BUTTON_MODE_POOL, PIN_BUTTON_MODE_CLEAN};

// #define CURRENT_MAX 1024
// #define CURRENT_MIN 0
// #define CURRENT_ZERO ((CURRENT_MAX+CURRENT_MIN)/2)

typedef enum {
	PORT_POOL,
	PORT_SPA,
	PORT_UNKNOWN
} t_port;

typedef enum {
    MODE_SPA,
    MODE_SPILL,
    MODE_POOL,
    MODE_CLEAN,
    MODE_UNKNOWN
} t_mode;

typedef enum {
    SPEED_OFF,
    SPEED_MIN,
    SPEED_LOW,
    SPEED_HI,
    SPEED_MAX
} t_speed;

typedef struct {
    unsigned short start_time_m;
    byte mode_speed;
    byte duration_5m;
} t_schedule_item;

#define SCHED_ITEM_BYTES 4
//#define EEPROM_SIZE (2 * 1024)  // 2 kB
#define SCHED_SLOTS 10

# endif // POOLBOT_H

